name: Deploy to Timeweb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: vh314.timeweb.ru
        username: co89321
        password: ${{ secrets.SFTP_PASSWORD }}
        local_path: './*'
        remote_path: '/home/c/co89321/public_html/test/github_cc_autodeploy'
        sftp_only: true
        delete_remote_files: false
