name: Notify Timeweb Server

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send deployment notification
      run: |
        echo "Push to master detected"
        echo "GitHub webhook will trigger deploy.php on server"
        echo "Check deploy.log on server for deployment status"
