name: Deploy to Timeweb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to server via rsync
      env:
        SSHPASS: ${{ secrets.FTP_PASSWORD }}
      run: |
        sshpass -e rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p 22" \
          --exclude='.git' \
          --exclude='.github' \
          ./ ${{ secrets.FTP_USERNAME }}@vh314.timeweb.ru:${{ secrets.DEPLOY_PATH }}/
