name: Deploy to FTP

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to production server
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: vh314.timeweb.ru
          protocol: ftps
          username: co89321_wdc
          password: Rd220911
          server-dir: /test/github_cc_autodeploy/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
