name: Deploy to Timeweb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy files via FTP
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: vh314.timeweb.ru
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: "./"
        remote_dir: "/test/github_cc_autodeploy"
        delete: "false"
